import CssBaseLine from '@/app/components/css.baseline'
import AppHeader from '@/app/components/app.header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
      </head>
      <body >
        <AppHeader />
        <CssBaseLine />
        {children}

      </body>
    </html>
  )
}
